pool:
  vmImage: 'windows-latest'

variables:
  azureSubscription: 'Azure-service-connection-1'
  azureFunctionAppName: 'Deploy-Dotnet-API'
  azureResourceGroupName: 'functionapp-rg'

stages:
- stage: Deploy
  jobs:
  - job: Deploy
    steps:
    - task: DownloadBuildArtifacts@0
      inputs:
        artifactName: 'drop'
        pipeline: samplefunction-dotnet8-CI
        buildVersionToDownload: 'latest'
        downloadPath: '$(System.ArtifactsDirectory)/${{ variables.Artifact_Path }}'

    - task: AzureFunctionApp@1
      inputs:
        azureSubscription: $(azureSubscription)
        appName: $(azureFunctionAppName)
        package: '$(System.ArtifactsDirectory)/drop/*.zip'
        resourceGroupName: $(azureResourceGroupName)
