pool:
  vmImage: 'windows-latest'

variables:
  azureSubscription: 'Azure-service-connection-1'
  azureFunctionAppName: 'DotNet8-Function-App'
  azureResourceGroupName: 'functionapp-rg'

stages:
- stage: Deploy
  jobs:
  - job: Deploy
    steps:

    - task: DownloadBuildArtifacts@1
      inputs:
        buildType: 'specific'
        project: 'efe1839c-42b9-4e88-a873-89fb8d14aff6'
        pipeline: '72'
        buildVersionToDownload: 'latest'
        downloadType: 'single'
        artifactName: 'drop'
        downloadPath: '$(System.ArtifactsDirectory)'

    - task: AzureFunctionApp@1
      inputs:
        azureSubscription: $(azureSubscription)
        appName: $(azureFunctionAppName)
        package: '$(System.ArtifactsDirectory)/drop/*.zip'
        resourceGroupName: $(azureResourceGroupName)
